apiVersion: batch/v1
kind: Job
metadata:
  name: create-alarm-table-job
  namespace: rest
spec:
  template:
    spec:
      containers:
      - name: create-alarm-table
        image: postgres:13
        env:
        - name: DB_NAME
          value: "alarmdb"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "admin"
        - name: DB_HOST
          value: "postgres-alarm-service"
        command: ["sh", "-c"]
        args:
        - |
          PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "
          CREATE TABLE IF NOT EXISTS alarms (
              id SERIAL PRIMARY KEY,
              rule_id INT NOT NULL,
              device_id UUID NOT NULL,
              data_type VARCHAR(100) NOT NULL,
              value NUMERIC NOT NULL,
              threshold_value NUMERIC NOT NULL,
              comparison_operator VARCHAR(10) NOT NULL,
              timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
              alarm_description TEXT NOT NULL
          );"
      restartPolicy: Never
  backoffLimit: 4
