apiVersion: v1
kind: Namespace
metadata:
  name: event
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-onboarder
  namespace: event
  labels:
    app: data-onboarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-onboarder
  template:
    metadata:
      labels:
        app: data-onboarder
    spec:
      containers:
      - name: data-onboarder
        image: data_onboarder:1
        ports:
        - containerPort: 8080
        env:
          - name: RABBITMQ_BROKER
            value: "rabbitmq-service"
          - name: RABBITMQ_USER
            value: "guest"
          - name: RABBITMQ_PASS
            value: "guest"
          - name: QUEUE
            value: "data-stream"
---
apiVersion: v1
kind: Service
metadata:
  name: data-onboarder-service
  namespace: event
  labels:
    app: data-onboarder
spec:
  selector:
    app: data-onboarder
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
  type: NodePort
