apiVersion: v1
kind: Namespace
metadata:
  name: file
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-app-deployment
  namespace: file
  labels:
    app: file-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-app
  template:
    metadata:
      labels:
        app: file-app
    spec:
      containers:
      - name: file-app
        image: file:0.0.2
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_FILE_PATH
          value: "/config/config.json"
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        hostPath:
          path: /tmp
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: file-app-service
  namespace: file
  labels:
    app: file-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30080
  selector:
    app: file-app
