apiVersion: batch/v1
kind: Job
metadata:
  name: create-tables-job
  namespace: db
spec:
  template:
    spec:
      containers:
      - name: create-tables
        image: postgres:13
        env:
        - name: DB_NAME
          value: "energydb"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "admin"
        - name: DB_HOST
          value: "postgres-service"
        command: ["sh", "-c"]
        args:
        - |
          PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "
          CREATE TABLE IF NOT EXISTS energy_data (
              data_id SERIAL PRIMARY KEY,
              device_id UUID,
              timestamp TIMESTAMP,
              type VARCHAR(100) NOT NULL,
              value NUMERIC NOT NULL
          );
          CREATE TABLE IF NOT EXISTS rules (
              id SERIAL PRIMARY KEY,
              device_id UUID NOT NULL,
              type VARCHAR(100) NOT NULL,
              comparison_operator VARCHAR(10) NOT NULL,
              threshold_value NUMERIC NOT NULL,
              severity TEXT NOT NULL,
              rule_description TEXT,
              UNIQUE (type, comparison_operator, threshold_value, device_id)
          );
          CREATE TABLE IF NOT EXISTS alarms (
              id SERIAL PRIMARY KEY,
              rule_id INT NOT NULL,
              device_id UUID NOT NULL,
              type VARCHAR(100) NOT NULL,
              value NUMERIC NOT NULL,
              threshold_value NUMERIC NOT NULL,
              comparison_operator VARCHAR(10) NOT NULL,
              timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
              alarm_description TEXT NOT NULL,
              FOREIGN KEY (rule_id) REFERENCES rules(id)
          );"
      restartPolicy: Never
  backoffLimit: 4
