apiVersion: v1
kind: Namespace
metadata:
  name: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rule-service
  namespace: db
  labels:
    app: rule-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rule-service
  template:
    metadata:
      labels:
        app: rule-service
    spec:
      containers:
      - name: rule-service
        image: rule_service:0.1
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_NAME
          value: "energydb"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: rule-service
  namespace: db
  labels:
    app: rule-service
spec:
  selector:
    app: rule-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30083
  type: NodePort