apiVersion: batch/v1
kind: Job
metadata:
  name: rule-update-job
  namespace: db
spec:
  template:
    spec:
      containers:
      - name: rule-update
        image: postgres:13
        env:
        - name: DB_NAME
          value: "energydb"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "admin"
        - name: DB_HOST
          value: "postgres-service"
        command: ["sh", "-c"]
        args:
        - |
          PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "
          ALTER TABLE rules
          ADD COLUMN consecutive_count INT DEFAULT 1 NOT NULL;"
      restartPolicy: Never
  backoffLimit: 4
